sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tEnMay4pRr2s6SzFmEX
    access-key-secret: MwiW5Y5ji46p29XuZ71dXokIbKDGy4
    bucket-name: chen-w-b